Add path array and default timezone
laminas/laminas-mvc-skeleton pull request #58
Opened 2022-08-17 08:04 UTC by voltan

Signed-off-by: Hossein Azizabadi Farahani <hossein.azizabadi@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

We use laminas as the main framework for some production applications (and [laminas-mvc-skeleton](https://github.com/laminas/laminas-mvc-skeleton)), in all of the applications as restful API, usually, our other paths like vendor and config is out of html folder and our folder system is different. I have to edit index.php after each install by custom path, 

It is good if we can set all paths in one array and just update it

2022-08-17 09:32 UTC, Ocramius requested changes
Closing here, mostly because addressing PR feedback requires re-doing the whole PR.

As for `ini_set()`, laminas generally attempts to **not** modify global state: that has held true for many years, and is one of the strengths of the framework.

2022-08-17 09:32 UTC, Ocramius commented on public/index.php
> +}
The framework itself should **NOT** adjust PHP globals.

This should come from your PHP settings, which are to be defined by you when building your production-ready docker containers (or whichever mechanism you use to provision production)

2022-08-17 09:32 UTC, Ocramius commented on public/index.php
> +include realpath($path['autoload']);
`realpath()` not required here

2022-08-17 09:32 UTC, Ocramius commented on public/index.php
> +$appConfig = require realpath($path['app_config']);
`realpath()` in general not required for `require` steps

2022-08-17 09:32 UTC, Ocramius commented on public/index.php
> +// Set paths
This comment doesn't do anything? :thinking:

2022-08-17 09:32 UTC, Ocramius commented on public/index.php
> +$path =  [
Can we give this variable a better (self-explanatory) name?

2022-08-17 09:32 UTC, Ocramius commented on public/index.php
> +if (file_exists($path['dev_config'])) {
The code written this way seems inefficient. Before, we just checked the paths directly, while now we put them in an array, then use specific keys of that array? :thinking:

2022-08-17 09:33 UTC, closed without merging

2022-08-19 05:11 UTC, voltan commented
Thank you very much for checking this pull request, As I said before, In all of our active projects, we had to change config paths in index.php,

I think if we put all paths in another config file ( for example boot.php inside of index.php ) and set paths on that file is better or just set paths on top of the index.

the problem is, that we don't have access to the config folder in this step. I use mvc-skeleton in all projects and we just develop modules, it's good if mvc-skeleton set some constant before running modules, for example, the default time zone for the project, but paths are more important I think

What is your idea? its a useful change if I just put paths in the boot.php file? for example like this : 
```
define('AUTOLOAD_FILE', __DIR__ . '/../vendor/autoload.php');
define('LAMINAS_APP_CONFIG', '__DIR__ . '/../config/application.config.php'');
define('LAMINAS_DEV_CONFIG', __DIR__ . '/../config/development.config.php');
```

And check it like this:

```
$appConfig = require  LAMINAS_APP_CONFIG;
```

Or something like this

2022-08-19 17:04 UTC, Ocramius commented
@voltan no, we don't pollute the global namespace: you shouldn't need those constants in first place, and if you are building standalone modules, you should be able to get the application config from the `'config'` service.

Autoloading also not necessary: it should already have been configured long before your module is in play.