Update bootstrap css to 5.1.3
laminas/laminas-mvc-skeleton pull request #69
Opened 2023-04-12 14:54 UTC by ThallesVFS

Update bootstrap css framework 4.4.1 to 5.1.3

2023-04-12 15:21 UTC, thalles commented
![image](https://user-images.githubusercontent.com/2185023/231504595-e4ab82d4-aeac-4c8f-9e9b-149c47dbe3bd.png)

2023-04-12 15:30 UTC, Xerkus commented
Is there a reason for 5.1.3 when latest is 5.2.3?

2023-04-12 15:48 UTC, Xerkus requested changes
jquery was dropped, its reference also needs to be removed from layout.

2023-04-12 16:03 UTC, thalles commented
Sorry!

2023-04-12 16:16 UTC, froschdesign requested changes

2023-04-12 16:16 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +    <div class="container-fluid py-5">
Why is the container used here?

2023-04-12 16:16 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
>              <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal &raquo;</a>
Please use a card footer for the buttons.

2023-04-12 16:16 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +  <div class="col">
Please use 4 spaces for indentation like above – everywhere.

2023-04-12 16:44 UTC, thalles commented
> Is there a reason for 5.1.3 when latest is 5.2.3?

Done!

2023-04-12 17:00 UTC, Xerkus approved these changes

2023-04-13 19:47 UTC, thalles commented
Hi @all!
Please check again

2023-04-13 19:51 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +    <div class="container-fluid py-5">
@thalles 
Can you please explain why the additional container is needed here?

2023-04-13 19:52 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +  <div class="col">
@thalles 
Please check again all indentations.

2023-04-14 07:48 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +    <div class="container-fluid py-5">
So it seems there was no need.

2023-04-18 01:04 UTC, thalles commented
Hey @everyone!
is anything still missing?

2023-04-18 06:44 UTC, froschdesign requested changes

2023-04-18 06:44 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +  <div class="col">
@thalles 
Please check again all indentations like this.

2023-04-18 06:44 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +    <div class="card h-100">
This one.

2023-04-18 06:44 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +    <div class="card h-100">
Also this.

2023-04-18 06:44 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +  </div>
This.

2023-04-18 06:44 UTC, froschdesign commented on module/Application/view/application/index/index.phtml
> +  </div>
And here.

2023-04-20 07:36 UTC, froschdesign requested changes
The `data` attributes have changed with version 5 of Bootstrap and need to be updated. Otherwise the [toogler for the navbar](https://getbootstrap.com/docs/5.2/components/navbar/#toggler) will not work.

https://getbootstrap.com/docs/5.2/migration/#javascript

2023-04-22 21:09 UTC, ThallesVFS commented
> The `data` attributes have changed with version 5 of Bootstrap and need to be updated. Otherwise the [toogler for the navbar](https://getbootstrap.com/docs/5.2/components/navbar/#toggler) will not work.
> 
> https://getbootstrap.com/docs/5.2/migration/#javascript

Done!

2023-04-26 14:26 UTC, ThallesVFS commented
Hi @froschdesign, let me know if missing something.
Thanks!

2023-04-26 18:40 UTC, froschdesign commented
@ThallesVFS 
When you are finished, mark this pull request as "Ready for review". In the meantime, I will test the changes locally.

2023-04-26 19:02 UTC, ThallesVFS commented
Sorry, it is my first time contributing for a open source on github.
Thanks for your help!

2023-05-02 07:11 UTC, froschdesign approved these changes

2023-05-02 07:21 UTC, Xerkus commented
Thank you.

2023-05-02 07:21 UTC, merged